# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gui_path/point_array.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import gui_path.msg

class point_array(genpy.Message):
  _md5sum = "b0e06ff95926b2506bb2cdfd45f68485"
  _type = "gui_path/point_array"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """path_point[] point_array
path_point[] obstacle_array
================================================================================
MSG: gui_path/path_point
int64 x
int64 y"""
  __slots__ = ['point_array','obstacle_array']
  _slot_types = ['gui_path/path_point[]','gui_path/path_point[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       point_array,obstacle_array

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(point_array, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.point_array is None:
        self.point_array = []
      if self.obstacle_array is None:
        self.obstacle_array = []
    else:
      self.point_array = []
      self.obstacle_array = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.point_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.point_array:
        _x = val1
        buff.write(_struct_2q.pack(_x.x, _x.y))
      length = len(self.obstacle_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.obstacle_array:
        _x = val1
        buff.write(_struct_2q.pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.point_array is None:
        self.point_array = None
      if self.obstacle_array is None:
        self.obstacle_array = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.point_array = []
      for i in range(0, length):
        val1 = gui_path.msg.path_point()
        _x = val1
        start = end
        end += 16
        (_x.x, _x.y,) = _struct_2q.unpack(str[start:end])
        self.point_array.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obstacle_array = []
      for i in range(0, length):
        val1 = gui_path.msg.path_point()
        _x = val1
        start = end
        end += 16
        (_x.x, _x.y,) = _struct_2q.unpack(str[start:end])
        self.obstacle_array.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.point_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.point_array:
        _x = val1
        buff.write(_struct_2q.pack(_x.x, _x.y))
      length = len(self.obstacle_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.obstacle_array:
        _x = val1
        buff.write(_struct_2q.pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.point_array is None:
        self.point_array = None
      if self.obstacle_array is None:
        self.obstacle_array = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.point_array = []
      for i in range(0, length):
        val1 = gui_path.msg.path_point()
        _x = val1
        start = end
        end += 16
        (_x.x, _x.y,) = _struct_2q.unpack(str[start:end])
        self.point_array.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obstacle_array = []
      for i in range(0, length):
        val1 = gui_path.msg.path_point()
        _x = val1
        start = end
        end += 16
        (_x.x, _x.y,) = _struct_2q.unpack(str[start:end])
        self.obstacle_array.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2q = struct.Struct("<2q")
